### ISSUE TITLE
[Reminder] Modify expected result of payment-request-in-iframe.html

### ISSUE THREAD

**Issue by alphan102** [mozilla-payments/gecko-dev#10]
We need to modify the expected result according to the latest spec.
https://github.com/w3c/browser-payment-api/pull/268/commits

Related Discussion in W3C spec
https://github.com/w3c/browser-payment-api/issues/2#issuecomment-238849573

**Comment by alphan102** [comment]
Here is the test file in our codebase. 
gecko-dev/testing/web-platform/tests/payment-request/payment-request-in-iframe.html

**Comment by bentian** [comment]
Maybe we can remove this test case. Since [allowpaymentrequest web-platform-tests](https://github.com/w3c/web-platform-tests/tree/master/payment-request/allowpaymentrequest) already covered tests of _allowpaymentrequest_ attribute, also the top-level restriction is removed from spec.

**Comment by marcoscaceres** [comment]
I've not checked the current state of the tests on the web platform tests side of things - so I don't have a strong opinion.

**Comment by bentian** [comment]
[allowpaymentrequest web-platform-tests](https://github.com/w3c/web-platform-tests/tree/master/payment-request/allowpaymentrequest) coverage reference: w3c/web-platform-tests#4526

**Comment by bentian** [comment]
w3c/web-platform-tests#6550

**Comment by bentian** [comment]
Close as above PR 6550 is merged.
