### ISSUE TITLE
Typo in PaymentRequest.cpp

### ISSUE THREAD

**Issue by pauljt** [mozilla-payments/gecko-dev#43]
There is a typo here: https://github.com/mozilla-payments/gecko-dev/blob/payment-dev/dom/payments/PaymentRequest.cpp#L43

Also just curious, these error messages seem quite verbose (notably we reflect the value passed in, back to the page). Is this normal for DOM APIs? Remember the mozContacts bug from FxOS ? (i.e. what happens if the web page passes in an object they dont have access to, e.g. cross-origin window.location object ?) I think webIDL should protect here (previous mozcontact issue was due to IDL) but I just wanted to raise it as something to think about.

**Comment by bentian** [comment]
Thanks for the catch! @alphan102, please help fix it.

Also do you have the mozContacts bug # for our reference? Here we only check the number merchant provides and throws error with message back to inform merchant per [spec](https://w3c.github.io/browser-payment-api/#constructor):
> Process the total:
>     If details.total.amount.value is not a valid decimal monetary value, then throw a TypeError; optionally informing the developer that the value is invalid.

**Comment by bentian** [comment]
The [mozContacts bug](https://bugzilla.mozilla.org/show_bug.cgi?id=856042) Paul refers to.

@marcoscaceres: any idea about Paul's question on DOM API error message convention?

**Comment by marcoscaceres** [comment]
> Also just curious, these error messages seem quite verbose (notably we reflect the value passed in, back to the page). Is this normal for DOM APIs?

Yes, it's normal. It's just that engines have done a poor job in the past in actually letting developers know what is going on. We (spec people) are trying to improve that. This API is particularly clumsy because you can have objects up to 4 levels deep - so not having good error would lead to debugging insanity.

**Comment by bentian** [comment]
Close via #44 and marcos' response.
