### ISSUE TITLE
Validate methodData in the request constructor

### ISSUE THREAD

**Issue by yrliou** [mozilla-payments/gecko-dev#45]
According to step 4 from https://www.w3.org/TR/payment-request/#constructor, we need to return TypeError if the length of methodData is 0 or the length of supportedMethods is 0 for any paymentMethod.

The [code comment](https://github.com/mozilla-payments/gecko-dev/blob/payment-dev/dom/payments/PaymentRequest.cpp#L166) here indicates the check is performed by webidl, not sure what it means exactly, but I think sequence with length 0 case won't be checked by webidl.
Feel free to correct me if I'm wrong. :)

**Comment by marcoscaceres** [comment]
I'll add a web platform test.

**Comment by marcoscaceres** [comment]
@yrliou, I think you are correct btw... it won't be checked by WebIDL. WebIDL will just check if it's an array.

**Comment by marcoscaceres** [comment]
Actually, there are two tests already in the test suite to check this. 

```JS
test(() => {
  assert_throws(
    {
      name: "TypeError",
    },
    () => {
      new PaymentRequest([], {
        total: {
          label: "",
          amount: {
            currency: "USD",
            value: "1.00",
          },
        },
      });
    }
  );
}, "If the length of the methodData sequence is zero, then throw a TypeError");

test(() => {
  assert_throws(
    {
      name: "TypeError",
    },
    () => {
      new PaymentRequest(
        [
          {
            supportedMethods: [],
          },
        ],
        {
          total: {
            label: "",
            amount: {
              currency: "USD",
              value: "1.00",
            },
          },
        }
      );
    }
  );
}, "If the length of the paymentMethod.supportedMethods sequence is zero, " + "then throw a TypeError");

```

**Comment by bentian** [comment]
Close via #47.
