### ISSUE TITLE
Some steps might be missing in updateWith()

### ISSUE THREAD

**Issue by yrliou** [mozilla-payments/gecko-dev#46]
From https://www.w3.org/TR/payment-request/#dom-paymentrequestupdateevent-updatewith(),
two bits are probably missing in current implementation?
4. If the dispatch flag is unset, then throw an " InvalidStateError" DOMException. 
8. Set event's stop propagation flag and stop immediate propagation flag.

**Comment by marcoscaceres** [comment]
Will make sure to add tests for these too.

**Comment by bentian** [comment]
Close via #48.
