### ISSUE TITLE
PaymentRequest constructor WebIDL error

### ISSUE THREAD

**Issue by bentian** [mozilla-payments/gecko-dev#5]
[PaymentRequest](https://www.w3.org/TR/payment-request/#paymentrequest-interface) constructor hits following [WebIDL error on gecko](http://searchfox.org/mozilla-central/source/dom/bindings/parser/WebIDL.py#4817): 
> WebIDLError: error: Dictionary argument or union argument containing a dictionary not followed by a required argument must be optional, /home/bentian/WORKSPACE/projects/gecko/web-payment/dom/webidl/PaymentRequest.webidl line 63:68
[Constructor(sequence<PaymentMethodData> methodData, PaymentDetails details, optional PaymentOptions options)

because argument **details** is 1) of dictionary [PaymentDetails](https://www.w3.org/TR/payment-request/#paymentdetails-dictionary) containing no required member and 2) not followed by a required argument, but is not an optional argument itself.

Note [Chrome implementation](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/payments/PaymentRequest.idl?l=10) doesn't seem to detect the error.

We should consider whether and how to revise W3C PaymentRequest API spec.
@marcoscaceres, any comment?

**Comment by bentian** [comment]
Related discussion:
- w3c/browser-payment-api#300: Should PaymentDetails.total be marked as required in IDL?
- w3c/browser-payment-api#320: PaymentDetails "total" member should be required

**Comment by marcoscaceres** [comment]
I'll try to get https://github.com/w3c/browser-payment-api/issues/320 fixed.

**Comment by bentian** [comment]
Closed via #13
